### PR TITLE
Make prettier help pages

### PR DESCRIPTION
**Pull request by fbreitwieser**
This PR implements help pages in MMSeqs2 that are (I think) easier to parse and more like help pages of other linux commands and bioinformatics tools.

Changes:
  - Put the default value in square brackets at the end of the description, instead of the second column.
 - Add the argument type to options, e.g. `-e FLOAT`
 - Specify the possible range of options by `(range FROM-TO)` at the end of the description, before the default value
 - Add some extra spacing (maybe not necessary)
 - Don't write `XXX options` for each option set, instead write the option set name alone
 - Add required positional argument descriptions when specifying `-h`. Currently I don't think any commands actually have this description, so maybe this shouldn't be shown.

Old:
image

New:
image

### CODE REVIEW

**Comment by milot-mirdita** [comment]
Hi Flo, thanks a lot that looks great!

Can you check if the `type_info` field you added in `Parameters.h` is needed? Is seems to be unused.

**Comment by soeding** [comment]
The new design is much prettier and easier to read. No objections or improvements from my side. Thanks so much!

**Comment by fbreitwieser** [comment]
Glad you like it! I'll fix the compile error.

> Can you check if the `type_info` field you added in `Parameters.h` is needed? Is seems to be unused.

You are correct, it's not used and I'll get rid of it.

**Comment by martin-steinegger** [comment]
Merged! 
Thanks a lot Flo.  :) 
We will make a new version of mmseqs2 soon including your changes.

**Pull request merged**
