### PR TITLE
Add command to extract Neff scores for MSA

### PR DESCRIPTION
**Pull request by neftlon**
As discussed in #638, this code adds a new command to output Neff scores. The command is called `profile2neff`. It takes a profile database as input and outputs per-residue Neff scores for a query sequence.

The scores are written to a `DBWriter` that then contains two lines for each sequence: a header similar to `profile2pssm`'s output and a line containing tab-separated Neff scores (from the range [1;255]) for each residue. The score is converted from the internal float representation to char using the `convertNeffToChar` function from `MathUtil.h`.

### CODE REVIEW

**Comment by neftlon** [comment]
It appears like some of the CI tests are not passing. Am I missing something or are parts of the CI pipeline broken? Can someone help me on that?

**Comment by milot-mirdita** [comment]
No idea why windows is failing in azure, you didn't change anything that would affect that. Cirrus is currently okay to fail, something changed on their side and I didn't get around to fix the issue.

I think you are still using the wrong function. Neff is stored as a char, you need to use `convertNeffToFloat` to convert it back.

**Comment by neftlon** [comment]
Ok good, then I will ignore these pipelines.

The Neff scores I use come from the `neffM` field of the `Sequence.h` class. According to the following code, these are stored as floats.

https://github.com/soedinglab/MMseqs2/blob/7b95387f93e38c3911f9188bc702d63ed3194013/src/commons/Sequence.h#L453

Therefore I think the `convertNeffToChar` function is more appropriate since it takes a Neff score that is stored a float. (The `convertNeffToFloat` function expects its parameter as an unsigned char, which I don't have when using said `neffM` field.)

https://github.com/soedinglab/MMseqs2/blob/7b95387f93e38c3911f9188bc702d63ed3194013/src/commons/MathUtil.h#L216-L224

Sorry if I am missing something here. Is there another location/a better way of extracting the Neff scores?

(I don't know whether this is just personal preference, but I like the idea of _values not being floats when writing_ them to an output. A fixed range from [1;255] somehow sound more appealing to me than a floating point number with an obscure precision.)

**Comment by milot-mirdita** [comment]
Okay, sorry I didn't remember the code very well. Your initial implementation without the MathUtil functions was correct, the Sequence object already deals with the correction to float. I wouldn't use `convertNeffToChar` here, it just spreads the possible range of Neffs (0 to 20, but more realistically 0 to 14) over the char range (0 to 255). I don't think it makes a lot of sense to print a value from 0 to 255.

**Comment by neftlon** [comment]
Sorry for the long round-trip delay, I've reverted my changes to the original implementation :)

**Comment by milot-mirdita** [comment]
Thank you. I was traveling and forgot about the PR, sorry!

**Pull request merged**
