### PR TITLE
SIMDe v0.7.1

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by milot-mirdita** [comment]
I unprefixed the MMseqs2 macros and replaced our undefined version xxhash with the latest release v0.8.
I'll merge once I get a green light from the CI. Thanks a lot :)

**Comment by mr-c** [comment]
@milot-mirdita Huzzah! 

Looks like https://travis-ci.org/github/soedinglab/MMseqs2/jobs/753198093 had a hiccup and needs restarting

BTW, I can remove the `lib/simde/simde/arm/` directory, if you wish, as there are not any NEON intrinsics in the MMSeqs2 code

**Comment by milot-mirdita** [comment]
I guess we could remove the arm subfolder, however it's already part of the git history anyway, so it doesn't change that much anymore. It would be nice to have a repo similar to `simde-no-tests`, but I don't want these to become a maintenance burden for you.

**Comment by mr-c** [comment]
@milot-mirdita Whatever works for you; if you don't mind the extra files then it is fine by me :-)

**Pull request merged**
