### PR TITLE
Remove leading space from convertmsa database output

### PR DESCRIPTION
**Pull request by chris-rands**
As I mentioned briefly in Issue #94 when I ran `convertmsa`, to generate an msa database from an input stockholm formatted alignment, the output database had a leading space after the `>` character on the first line, which then caused `msa2profile` to output various "Invalid" messages.

Removing the leading space as applied in the pull request seems to fix this issue. I don't think my input stockholm format alignment was the cause, since I tried generating this with 2 independent tools. 
However, I am not familiar with either file format and I may easily have overlooked something; also I am not a C++ programmer and I did't try testing this change on any unit tests, so I hope it does not break anything else!

Here's a full example (I can also provide the `TEST.sth` input data if required) and let me know if more details are needed, thank you!

Edit: I am running this on Arch Linux.

```
$ mmseqs convertmsa TEST.sth TEST.db
Program call:
TEST.sth TEST.db 

MMseqs Version: 	11ef9eb2c1dfbdb4c661df80e1b0314207f6da46
Identifier Field	1
Verbosity       	3

Time for merging files: 0 h 0 m 0 s

Done.
$ head -n 2 TEST.db
> db-CARD.1.1.3_geneId-AAA22081.1_desc-cat_annot-ARO3002670_taxaName-Agrobacterium.tumefaciens.str..C58_taxaId-176299
MENYFESPFRGITLDKQVKSPNLVVGKYSYYSGYYHGHSFEDCARYLLPDE-GADRLVIGSFCSIGSGAAFIMAGNQGHRNEWISTFPFFFMPEVPEFENAANGYLPAGDTVIGNDVWIGSEAIIMPGITVGDGAVIGTRALVTKDVEPYAIVGGNPAKTIRKRFDDDSIALLLEMKWWGWPAERLKAAMPLMTSGNVAALYRFWRSDSL----------
$ mmseqs msa2profile TEST.db TEST.profile --match-mode 1 --msa-type 2 --threads 1
Program call:
TEST.db TEST.profile --match-mode 1 --msa-type 2 --threads 1 

MMseqs Version:                    	1944b9783e5a01e722bd519c9792f006aa180b8d
MSA type                           	2
Sub Matrix                         	blosum62.out
Match mode                         	1
Match ratio                        	0.5
Pseudo count a                     	0
Pseudo count b                     	1.5
Compositional bias                 	1
Use global sequence weighting      	false
Filter MSA                         	1
Minimum coverage                   	0
Minimum seq. id.                   	0
Minimum score per column           	-20
Maximum sequence identity threshold	0.9
Select n most diverse seqs         	1000
Threads                            	1
Verbosity                          	3

Finding maximum sequence length and set size.
Compute profiles from MSAs.
Invalid fasta sequence 0 in entry 0!
Invalid msa 0! Skipping entry.
Time for merging files: 0 h 0 m 0 s
Time for merging files: 0 h 0 m 0 s
Time for merging files: 0 h 0 m 0 s
Time for merging files: 0 h 0 m 1 s
Time for processing: 0 h 0 m 2s
```

### CODE REVIEW

**Comment by milot-mirdita** [comment]
Thanks, that was a pretty sloppy fix of mine.

By default, we read the AC field from the STOCKHOLM header as the identifier in `convertmsa`.
I guess your profiles do not contain an AC field and the `identifier` variable remains empty, leading to a prepended space character.

You can instead use `--identifier-field 0` in `convertmsa` to use the ID field, that always should exist. Then the code with the appended space makes sense.

Without that space character (for PFAM at least) you would get a gibberish identifier like:
`PF10417.8S6ENI5_9CLOT/170-197`

I will think about how to make this better, i hope `convertmsa --identifier-field 0` is a good workaround.

**Comment by chris-rands** [comment]
Thank you! Sorry it was premature of me to make a PR without understanding the issue, and I can see I am breaking something. However, I haven't yet got your workaround to work (I get the same "Invalid" messages, even after running with `--identifier-field 0 ` flag), I think this is because my stockholm header is only 2 lines (no AC or ID fields)? If these are compulsory fields then the problem is not yours but with the way I generate the stockholm alignment via Biopython? If so, then let me know I can fix this in Biopython

My input file looks like this generated from a fasta MSA:

```
$ head -n 3 TEST.sth
# STOCKHOLM 1.0
#=GF SQ 19
db-CARD.1.1.3_geneId-AAA22081.1_desc-cat_annot-ARO3002670_taxaName-Agrobacterium.tumefaciens.str..C58_taxaId-176299 MENYFESPFRGITLDKQVKSPNLVVGKYSYYSGYYHGHSFEDCARYLLPDE-GADRLVIGSFCSIGSGAAFIMAGNQGHRNEWISTFPFFFMPEVPEFENAANGYLPAGDTVIGNDVWIGSEAIIMPGITVGDGAVIGTRALVTKDVEPYAIVGGNPAKTIRKRFDDDSIALLLEMKWWGWPAERLKAAMPLMTSGNVAALYRFWRSDSL----------
```

**Comment by milot-mirdita** [comment]
That makes sense, I expected it to have some header.

In this case it would be okay for you, if the identifier of the alignment would be the name of the first sequence?

**Comment by chris-rands** [comment]
Yes thank you, but I can trivially add some extra header fields to the stockholm files if they are meant to be there

**Comment by chris-rands** [comment]
Perhaps one option would be to raise an error in `convertmsa` with a helpful message when the user specifies an identifier field that is absent from the stockholm file?

**Comment by milot-mirdita** [comment]
Sorry for the delay. I think this should improve the situation:
https://github.com/soedinglab/MMseqs2/commit/c5594768f9ea8070deeecc329e33d3a486bc95d7

If no comment fields exist, the name of the first sequence will be chosen.

**Comment by chris-rands** [comment]
Ok thanks again!

**Pull request closed without merging**
